---
title: "Consult a Digital Research Specialist"
subtitle: "For help and advice in applying digital skills to your research"
format:
  html:
    toc: false
    echo: false
    keep-hidden: true
    code-tools: false
    css:
      - index-header.css
---

::: consultation-button-container
[Request a
consultation](https://docs.google.com/forms/d/e/1FAIpQLSfZzkuJIe5j5dADrvhOsB_CILZ_QExxxFESWph_69tGfLZw4Q/viewform?embedded=true){.consultation-button
.external target="_self"}
:::

[{{< fa solid puzzle-piece >}}]{style="display: none;"}

### Do you need advice on a specific problem, help choosing the right tools, or guidance from someone who has tackled a similar challenge before? 
Researchers from across the UK can book a one-to-one discussion with one of our Digital Research Infrastructure specialists and get practical advice tailored to their project.

Whether you’re a PhD student taking your first steps into data-intensive research, a postdoctoral researcher exploring new methods, an academic leading a project, or a research group looking for specialist advice, we’re here to help.

We also welcome professional services staff supporting researchers, as well as colleagues from industry and the public sector who want to learn more about digital tools, data management, AI, bioinformatics, and other research technologies.

Whatever your background or level of experience, our experts can help you find practical solutions and useful next steps.

### It’s completely **free to use** too! All the cost of the service is covered by the UKRI.

# Get help to...

```{=html}
<div id="consult-cards">

<div class="consult-card">
  <div class="icon">
    <i class="fa-solid fa-puzzle-piece"></i>
  </div>
  <h3>Tackle Analytical Problems</h3>
  <p>Get fresh perspectives on complex data analysis and research methodology.</p>
</div>

<div class="consult-card">
  <div class="icon">
    <i class="fa-solid fa-code"></i>
  </div>
  <h3>Debug Your Code</h3>
  <p>Resolve coding issues and learn best practices for research software development.</p>
</div>

<div class="consult-card">
  <div class="icon">
    <i class="fa-solid fa-database"></i>
  </div>
  <h3>Manage Research Data</h3>
  <p>Design effective strategies for organizing, storing, and sharing your research data.</p>
</div>


</div>
```
