---
title: "UKRI Digital Research Skills Catalyst"
---

**Unlock your potential with the UKRI Digital Research Skills Catalyst – the national hub for researcher and innovator development.**

## Project history and funding

Led by Professor Emma Rand at the University of York, the Catalyst Project was developed in response to the UKRI Digital Research Infrastructure Programme funding call.
It brings together seven university partners in a collaborative effort to centralise high-quality training materials for researchers and innovators. 

The project builds on resources created by Data Science in Healthcare & Biosciences (DaSH), which developed training materials and hosted events between 2021 and 2023 to upskill health and bioscience researchers in data management and analysis.
The Catalyst now centralises access to materials from seven of the nine DaSH projects, creating a single hub for researchers to access these resources.

While originally focused on health and bioscience researchers, the Catalyst aims to reach a broader audience.
Its digital research skills training resources are also highly relevant for researchers in arts and humanities, sciences, and social sciences, providing opportunities to enhance digital expertise across disciplines.
